<?php
/**
 * AdvertisementsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bazos.cz API
 *
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdvertisementsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdvertisementsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteAdvertisement
     *
     * Deletes your advertisement from bazos.cz.
     *
     */
    public function testDeleteAdvertisement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOwnAdvertisements
     *
     * Downloads your own advertisements from bazos.cz including photos.
     *
     */
    public function testListOwnAdvertisements()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scrapeOwnAdvertisement
     *
     * Scrapes your own advertisement from bazos.cz including photos.
     *
     */
    public function testScrapeOwnAdvertisement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadAdvertisement
     *
     * Uploads an advertisement to bazos.cz.
     *
     */
    public function testUploadAdvertisement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
