/**
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BazosCzApi);
  }
}(this, function(expect, BazosCzApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BazosCzApi.AdvertisementsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdvertisementsApi', function() {
    describe('deleteAdvertisement', function() {
      it('should call deleteAdvertisement successfully', function(done) {
        //uncomment below and update the code to test deleteAdvertisement
        //instance.deleteAdvertisement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listOwnAdvertisements', function() {
      it('should call listOwnAdvertisements successfully', function(done) {
        //uncomment below and update the code to test listOwnAdvertisements
        //instance.listOwnAdvertisements(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scrapeOwnAdvertisement', function() {
      it('should call scrapeOwnAdvertisement successfully', function(done) {
        //uncomment below and update the code to test scrapeOwnAdvertisement
        //instance.scrapeOwnAdvertisement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadAdvertisement', function() {
      it('should call uploadAdvertisement successfully', function(done) {
        //uncomment below and update the code to test uploadAdvertisement
        //instance.uploadAdvertisement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
