/*
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Advertisement;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.UploadRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdvertisementsApi
 */
@Disabled
class AdvertisementsApiTest {

    private final AdvertisementsApi api = new AdvertisementsApi();

    
    /**
     * Deletes your advertisement from bazos.cz
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void deleteAdvertisementTest() {
        String url = null;
        String password = null;

        Boolean response = api.deleteAdvertisement(url, password);

        // TODO: test validations
    }
    
    /**
     * Downloads your own advertisements from bazos.cz including photos
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void listOwnAdvertisementsTest() {
        String email = null;
        String phone = null;
        String password = null;
        Boolean downloadPhotos = null;

        List<Advertisement> response = api.listOwnAdvertisements(email, phone, password, downloadPhotos);

        // TODO: test validations
    }
    
    /**
     * Scrapes your own advertisement from bazos.cz including photos
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void scrapeOwnAdvertisementTest() {
        String url = null;
        String password = null;
        Boolean downloadPhotos = null;

        Advertisement response = api.scrapeOwnAdvertisement(url, password, downloadPhotos);

        // TODO: test validations
    }
    
    /**
     * Uploads an advertisement to bazos.cz
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void uploadAdvertisementTest() {
        UploadRequest uploadRequest = null;

        Integer response = api.uploadAdvertisement(uploadRequest);

        // TODO: test validations
    }
    
}
