/*
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Disabled
class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    
    /**
     * Verifies the bazos ID and bazos code are valid. If this fails you need to authenticate again.
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void checkCredentialsTest() {
        Long bid = null;
        String bkod = null;

        Boolean response = api.checkCredentials(bid, bkod);

        // TODO: test validations
    }
    
    /**
     * Requests a code on your phone to authenticate for using bazos.cz
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void requestAuthenticationCodeTest() {
        String phone = null;

        String response = api.requestAuthenticationCode(phone);

        // TODO: test validations
    }
    
    /**
     * Sends an authentication code, obtained via text message on your phone, back to bazos.cz
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void submitAuthenticationCodeTest() {
        String code = null;
        String phone = null;

        Map<String, String> response = api.submitAuthenticationCode(code, phone);

        // TODO: test validations
    }
    
}
