# coding: utf-8

"""
    Bazos.cz API

    This is a REST API for bazos.cz

    The version of the OpenAPI document: v0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.advertisements_api import AdvertisementsApi


class TestAdvertisementsApi(unittest.TestCase):
    """AdvertisementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdvertisementsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_advertisement(self) -> None:
        """Test case for delete_advertisement

        Deletes your advertisement from bazos.cz
        """
        pass

    def test_list_own_advertisements(self) -> None:
        """Test case for list_own_advertisements

        Downloads your own advertisements from bazos.cz including photos
        """
        pass

    def test_scrape_own_advertisement(self) -> None:
        """Test case for scrape_own_advertisement

        Scrapes your own advertisement from bazos.cz including photos
        """
        pass

    def test_upload_advertisement(self) -> None:
        """Test case for upload_advertisement

        Uploads an advertisement to bazos.cz
        """
        pass


if __name__ == '__main__':
    unittest.main()
