# coding: utf-8

"""
    Bazos.cz API

    This is a REST API for bazos.cz

    The version of the OpenAPI document: v0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.main_category import MainCategory

class TestMainCategory(unittest.TestCase):
    """MainCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MainCategory:
        """Test MainCategory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MainCategory`
        """
        model = MainCategory()
        if include_optional:
            return MainCategory(
                url = '',
                title = '',
                id = 56
            )
        else:
            return MainCategory(
        )
        """

    def testMainCategory(self):
        """Test MainCategory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
