# coding: utf-8

"""
    Bazos.cz API

    This is a REST API for bazos.cz

    The version of the OpenAPI document: v0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.seller import Seller

class TestSeller(unittest.TestCase):
    """Seller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Seller:
        """Test Seller
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Seller`
        """
        model = Seller()
        if include_optional:
            return Seller(
                phone = '',
                email = '',
                ad_seller_name = '',
                ad_phone = '',
                ad_email = '',
                ad_zip = '',
                ad_password = ''
            )
        else:
            return Seller(
        )
        """

    def testSeller(self):
        """Test Seller"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
