<?php
/**
 * Seller
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bazos.cz API
 *
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Seller Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Seller implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Seller';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'phone' => 'string',
        'email' => 'string',
        'ad_seller_name' => 'string',
        'ad_phone' => 'string',
        'ad_email' => 'string',
        'ad_zip' => 'string',
        'ad_password' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'phone' => null,
        'email' => null,
        'ad_seller_name' => null,
        'ad_phone' => null,
        'ad_email' => null,
        'ad_zip' => null,
        'ad_password' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'phone' => false,
        'email' => false,
        'ad_seller_name' => false,
        'ad_phone' => false,
        'ad_email' => false,
        'ad_zip' => false,
        'ad_password' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'phone' => 'phone',
        'email' => 'email',
        'ad_seller_name' => 'adSellerName',
        'ad_phone' => 'adPhone',
        'ad_email' => 'adEmail',
        'ad_zip' => 'adZip',
        'ad_password' => 'adPassword'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'ad_seller_name' => 'setAdSellerName',
        'ad_phone' => 'setAdPhone',
        'ad_email' => 'setAdEmail',
        'ad_zip' => 'setAdZip',
        'ad_password' => 'setAdPassword'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'ad_seller_name' => 'getAdSellerName',
        'ad_phone' => 'getAdPhone',
        'ad_email' => 'getAdEmail',
        'ad_zip' => 'getAdZip',
        'ad_password' => 'getAdPassword'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('ad_seller_name', $data ?? [], null);
        $this->setIfExists('ad_phone', $data ?? [], null);
        $this->setIfExists('ad_email', $data ?? [], null);
        $this->setIfExists('ad_zip', $data ?? [], null);
        $this->setIfExists('ad_password', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets ad_seller_name
     *
     * @return string|null
     */
    public function getAdSellerName()
    {
        return $this->container['ad_seller_name'];
    }

    /**
     * Sets ad_seller_name
     *
     * @param string|null $ad_seller_name ad_seller_name
     *
     * @return self
     */
    public function setAdSellerName($ad_seller_name)
    {
        if (is_null($ad_seller_name)) {
            throw new \InvalidArgumentException('non-nullable ad_seller_name cannot be null');
        }
        $this->container['ad_seller_name'] = $ad_seller_name;

        return $this;
    }

    /**
     * Gets ad_phone
     *
     * @return string|null
     */
    public function getAdPhone()
    {
        return $this->container['ad_phone'];
    }

    /**
     * Sets ad_phone
     *
     * @param string|null $ad_phone ad_phone
     *
     * @return self
     */
    public function setAdPhone($ad_phone)
    {
        if (is_null($ad_phone)) {
            throw new \InvalidArgumentException('non-nullable ad_phone cannot be null');
        }
        $this->container['ad_phone'] = $ad_phone;

        return $this;
    }

    /**
     * Gets ad_email
     *
     * @return string|null
     */
    public function getAdEmail()
    {
        return $this->container['ad_email'];
    }

    /**
     * Sets ad_email
     *
     * @param string|null $ad_email ad_email
     *
     * @return self
     */
    public function setAdEmail($ad_email)
    {
        if (is_null($ad_email)) {
            throw new \InvalidArgumentException('non-nullable ad_email cannot be null');
        }
        $this->container['ad_email'] = $ad_email;

        return $this;
    }

    /**
     * Gets ad_zip
     *
     * @return string|null
     */
    public function getAdZip()
    {
        return $this->container['ad_zip'];
    }

    /**
     * Sets ad_zip
     *
     * @param string|null $ad_zip ad_zip
     *
     * @return self
     */
    public function setAdZip($ad_zip)
    {
        if (is_null($ad_zip)) {
            throw new \InvalidArgumentException('non-nullable ad_zip cannot be null');
        }
        $this->container['ad_zip'] = $ad_zip;

        return $this;
    }

    /**
     * Gets ad_password
     *
     * @return string|null
     */
    public function getAdPassword()
    {
        return $this->container['ad_password'];
    }

    /**
     * Sets ad_password
     *
     * @param string|null $ad_password ad_password
     *
     * @return self
     */
    public function setAdPassword($ad_password)
    {
        if (is_null($ad_password)) {
            throw new \InvalidArgumentException('non-nullable ad_password cannot be null');
        }
        $this->container['ad_password'] = $ad_password;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


