/*
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Seller
 */
@JsonPropertyOrder({
  Seller.JSON_PROPERTY_PHONE,
  Seller.JSON_PROPERTY_EMAIL,
  Seller.JSON_PROPERTY_AD_SELLER_NAME,
  Seller.JSON_PROPERTY_AD_PHONE,
  Seller.JSON_PROPERTY_AD_EMAIL,
  Seller.JSON_PROPERTY_AD_ZIP,
  Seller.JSON_PROPERTY_AD_PASSWORD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-14T11:45:00.040478100+02:00[Europe/Prague]", comments = "Generator version: 7.8.0")
public class Seller {
  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_AD_SELLER_NAME = "adSellerName";
  private String adSellerName;

  public static final String JSON_PROPERTY_AD_PHONE = "adPhone";
  private String adPhone;

  public static final String JSON_PROPERTY_AD_EMAIL = "adEmail";
  private String adEmail;

  public static final String JSON_PROPERTY_AD_ZIP = "adZip";
  private String adZip;

  public static final String JSON_PROPERTY_AD_PASSWORD = "adPassword";
  private String adPassword;

  public Seller() {
  }

  public Seller phone(String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Seller email(String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }

  public Seller adSellerName(String adSellerName) {
    
    this.adSellerName = adSellerName;
    return this;
  }

  /**
   * Get adSellerName
   * @return adSellerName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AD_SELLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdSellerName() {
    return adSellerName;
  }


  @JsonProperty(JSON_PROPERTY_AD_SELLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdSellerName(String adSellerName) {
    this.adSellerName = adSellerName;
  }

  public Seller adPhone(String adPhone) {
    
    this.adPhone = adPhone;
    return this;
  }

  /**
   * Get adPhone
   * @return adPhone
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AD_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdPhone() {
    return adPhone;
  }


  @JsonProperty(JSON_PROPERTY_AD_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdPhone(String adPhone) {
    this.adPhone = adPhone;
  }

  public Seller adEmail(String adEmail) {
    
    this.adEmail = adEmail;
    return this;
  }

  /**
   * Get adEmail
   * @return adEmail
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AD_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdEmail() {
    return adEmail;
  }


  @JsonProperty(JSON_PROPERTY_AD_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdEmail(String adEmail) {
    this.adEmail = adEmail;
  }

  public Seller adZip(String adZip) {
    
    this.adZip = adZip;
    return this;
  }

  /**
   * Get adZip
   * @return adZip
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AD_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdZip() {
    return adZip;
  }


  @JsonProperty(JSON_PROPERTY_AD_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdZip(String adZip) {
    this.adZip = adZip;
  }

  public Seller adPassword(String adPassword) {
    
    this.adPassword = adPassword;
    return this;
  }

  /**
   * Get adPassword
   * @return adPassword
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AD_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdPassword() {
    return adPassword;
  }


  @JsonProperty(JSON_PROPERTY_AD_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdPassword(String adPassword) {
    this.adPassword = adPassword;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Seller seller = (Seller) o;
    return Objects.equals(this.phone, seller.phone) &&
        Objects.equals(this.email, seller.email) &&
        Objects.equals(this.adSellerName, seller.adSellerName) &&
        Objects.equals(this.adPhone, seller.adPhone) &&
        Objects.equals(this.adEmail, seller.adEmail) &&
        Objects.equals(this.adZip, seller.adZip) &&
        Objects.equals(this.adPassword, seller.adPassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, email, adSellerName, adPhone, adEmail, adZip, adPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Seller {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    adSellerName: ").append(toIndentedString(adSellerName)).append("\n");
    sb.append("    adPhone: ").append(toIndentedString(adPhone)).append("\n");
    sb.append("    adEmail: ").append(toIndentedString(adEmail)).append("\n");
    sb.append("    adZip: ").append(toIndentedString(adZip)).append("\n");
    sb.append("    adPassword: ").append(toIndentedString(adPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

