/*
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.Advertisement;
import org.openapitools.client.model.Seller;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UploadRequest
 */
@JsonPropertyOrder({
  UploadRequest.JSON_PROPERTY_BID,
  UploadRequest.JSON_PROPERTY_BKOD,
  UploadRequest.JSON_PROPERTY_ADVERTISEMENT,
  UploadRequest.JSON_PROPERTY_SELLER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-14T11:45:00.040478100+02:00[Europe/Prague]", comments = "Generator version: 7.8.0")
public class UploadRequest {
  public static final String JSON_PROPERTY_BID = "bid";
  private String bid;

  public static final String JSON_PROPERTY_BKOD = "bkod";
  private String bkod;

  public static final String JSON_PROPERTY_ADVERTISEMENT = "advertisement";
  private Advertisement advertisement;

  public static final String JSON_PROPERTY_SELLER = "seller";
  private Seller seller;

  public UploadRequest() {
  }

  public UploadRequest bid(String bid) {
    
    this.bid = bid;
    return this;
  }

  /**
   * Get bid
   * @return bid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBid() {
    return bid;
  }


  @JsonProperty(JSON_PROPERTY_BID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBid(String bid) {
    this.bid = bid;
  }

  public UploadRequest bkod(String bkod) {
    
    this.bkod = bkod;
    return this;
  }

  /**
   * Get bkod
   * @return bkod
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BKOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBkod() {
    return bkod;
  }


  @JsonProperty(JSON_PROPERTY_BKOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBkod(String bkod) {
    this.bkod = bkod;
  }

  public UploadRequest advertisement(Advertisement advertisement) {
    
    this.advertisement = advertisement;
    return this;
  }

  /**
   * Get advertisement
   * @return advertisement
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADVERTISEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Advertisement getAdvertisement() {
    return advertisement;
  }


  @JsonProperty(JSON_PROPERTY_ADVERTISEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvertisement(Advertisement advertisement) {
    this.advertisement = advertisement;
  }

  public UploadRequest seller(Seller seller) {
    
    this.seller = seller;
    return this;
  }

  /**
   * Get seller
   * @return seller
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Seller getSeller() {
    return seller;
  }


  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeller(Seller seller) {
    this.seller = seller;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadRequest uploadRequest = (UploadRequest) o;
    return Objects.equals(this.bid, uploadRequest.bid) &&
        Objects.equals(this.bkod, uploadRequest.bkod) &&
        Objects.equals(this.advertisement, uploadRequest.advertisement) &&
        Objects.equals(this.seller, uploadRequest.seller);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bid, bkod, advertisement, seller);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadRequest {\n");
    sb.append("    bid: ").append(toIndentedString(bid)).append("\n");
    sb.append("    bkod: ").append(toIndentedString(bkod)).append("\n");
    sb.append("    advertisement: ").append(toIndentedString(advertisement)).append("\n");
    sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

