/**
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Photo from './Photo';
import SubCategory from './SubCategory';

/**
 * The Advertisement model module.
 * @module model/Advertisement
 * @version v0.9.2
 */
class Advertisement {
    /**
     * Constructs a new <code>Advertisement</code>.
     * @alias module:model/Advertisement
     */
    constructor() { 
        
        Advertisement.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Advertisement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Advertisement} obj Optional instance to populate.
     * @return {module:model/Advertisement} The populated <code>Advertisement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Advertisement();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('photos')) {
                obj['photos'] = ApiClient.convertToType(data['photos'], [Photo]);
            }
            if (data.hasOwnProperty('subCategory')) {
                obj['subCategory'] = SubCategory.constructFromObject(data['subCategory']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Advertisement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Advertisement</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['photos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['photos'])) {
                throw new Error("Expected the field `photos` to be an array in the JSON data but got " + data['photos']);
            }
            // validate the optional field `photos` (array)
            for (const item of data['photos']) {
                Photo.validateJSON(item);
            };
        }
        // validate the optional field `subCategory`
        if (data['subCategory']) { // data not null
          SubCategory.validateJSON(data['subCategory']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Advertisement.prototype['id'] = undefined;

/**
 * @member {String} url
 */
Advertisement.prototype['url'] = undefined;

/**
 * @member {String} date
 */
Advertisement.prototype['date'] = undefined;

/**
 * @member {String} title
 */
Advertisement.prototype['title'] = undefined;

/**
 * @member {Number} price
 */
Advertisement.prototype['price'] = undefined;

/**
 * @member {String} description
 */
Advertisement.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/Photo>} photos
 */
Advertisement.prototype['photos'] = undefined;

/**
 * @member {module:model/SubCategory} subCategory
 */
Advertisement.prototype['subCategory'] = undefined;






export default Advertisement;

