/*
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Seller
 */
class SellerTest {
    private final Seller model = new Seller();

    /**
     * Model tests for Seller
     */
    @Test
    void testSeller() {
        // TODO: test Seller
    }

    /**
     * Test the property 'phone'
     */
    @Test
    void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'adSellerName'
     */
    @Test
    void adSellerNameTest() {
        // TODO: test adSellerName
    }

    /**
     * Test the property 'adPhone'
     */
    @Test
    void adPhoneTest() {
        // TODO: test adPhone
    }

    /**
     * Test the property 'adEmail'
     */
    @Test
    void adEmailTest() {
        // TODO: test adEmail
    }

    /**
     * Test the property 'adZip'
     */
    @Test
    void adZipTest() {
        // TODO: test adZip
    }

    /**
     * Test the property 'adPassword'
     */
    @Test
    void adPasswordTest() {
        // TODO: test adPassword
    }

}
