/*
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.Advertisement;
import org.openapitools.client.model.Seller;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UploadRequest
 */
class UploadRequestTest {
    private final UploadRequest model = new UploadRequest();

    /**
     * Model tests for UploadRequest
     */
    @Test
    void testUploadRequest() {
        // TODO: test UploadRequest
    }

    /**
     * Test the property 'bid'
     */
    @Test
    void bidTest() {
        // TODO: test bid
    }

    /**
     * Test the property 'bkod'
     */
    @Test
    void bkodTest() {
        // TODO: test bkod
    }

    /**
     * Test the property 'advertisement'
     */
    @Test
    void advertisementTest() {
        // TODO: test advertisement
    }

    /**
     * Test the property 'seller'
     */
    @Test
    void sellerTest() {
        // TODO: test seller
    }

}
