# coding: utf-8

# flake8: noqa
"""
    Bazos.cz API

    This is a REST API for bazos.cz

    The version of the OpenAPI document: v0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.advertisement import Advertisement
from openapi_client.models.error import Error
from openapi_client.models.main_category import MainCategory
from openapi_client.models.photo import Photo
from openapi_client.models.seller import Seller
from openapi_client.models.sub_category import SubCategory
from openapi_client.models.upload_request import UploadRequest
