# coding: utf-8

"""
    Bazos.cz API

    This is a REST API for bazos.cz

    The version of the OpenAPI document: v0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.advertisement import Advertisement
from openapi_client.models.seller import Seller
from typing import Optional, Set
from typing_extensions import Self

class UploadRequest(BaseModel):
    """
    UploadRequest
    """ # noqa: E501
    bid: Optional[StrictStr] = None
    bkod: Optional[StrictStr] = None
    advertisement: Optional[Advertisement] = None
    seller: Optional[Seller] = None
    __properties: ClassVar[List[str]] = ["bid", "bkod", "advertisement", "seller"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UploadRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of advertisement
        if self.advertisement:
            _dict['advertisement'] = self.advertisement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of seller
        if self.seller:
            _dict['seller'] = self.seller.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UploadRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bid": obj.get("bid"),
            "bkod": obj.get("bkod"),
            "advertisement": Advertisement.from_dict(obj["advertisement"]) if obj.get("advertisement") is not None else None,
            "seller": Seller.from_dict(obj["seller"]) if obj.get("seller") is not None else None
        })
        return _obj


