/**
 * Bazos.cz API
 * This is a REST API for bazos.cz
 *
 * The version of the OpenAPI document: v0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BazosCzApi);
  }
}(this, function(expect, BazosCzApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BazosCzApi.Seller();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Seller', function() {
    it('should create an instance of Seller', function() {
      // uncomment below and update the code to test Seller
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be.a(BazosCzApi.Seller);
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be();
    });

    it('should have the property adSellerName (base name: "adSellerName")', function() {
      // uncomment below and update the code to test the property adSellerName
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be();
    });

    it('should have the property adPhone (base name: "adPhone")', function() {
      // uncomment below and update the code to test the property adPhone
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be();
    });

    it('should have the property adEmail (base name: "adEmail")', function() {
      // uncomment below and update the code to test the property adEmail
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be();
    });

    it('should have the property adZip (base name: "adZip")', function() {
      // uncomment below and update the code to test the property adZip
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be();
    });

    it('should have the property adPassword (base name: "adPassword")', function() {
      // uncomment below and update the code to test the property adPassword
      //var instance = new BazosCzApi.Seller();
      //expect(instance).to.be();
    });

  });

}));
